# EVOLVE-BLOCK-START
"""ODE discovery seed for normalized multi-dataset amyloid aggregation kinetics."""

from __future__ import annotations

from typing import Any

import sympy as sp
from numpy.typing import NDArray

from pysr_harness.equation_session import (
    constant_symbols,
    evaluate_expression,
    feature_symbols,
)


def evaluate_symbolic_candidate(
    X_train: NDArray,
    y_train: NDArray,
    X_val: NDArray,
    y_val: NDArray,
) -> dict[str, Any]:
    """
    Generic bounded aggregation-rate ODE.

    This seed starts from a broad mechanism class rather than a specific
    closed-form solution: a concentration-independent source term can create
    onset from near-zero signal, while an autocatalytic state-dependent term
    can sharpen growth once aggregates are present.  Monomer and seed features
    modulate both routes, and a capacity factor keeps the trajectory saturating
    toward a fitted plateau.

    Features: x0 = normalized time, x1 = initial monomer m0, x2 = initial
    seed/aggregate M0, and x3 = current normalized concentration/state.
    """
    x = feature_symbols(X_train.shape[1])
    c = constant_symbols(10)

    time = x[0]
    monomer = x[1]
    seed = x[2]
    concentration = x[3]

    # Knowles-Cohen reduced master equation in converted mass fraction c, made
    # fully autonomous (no explicit-time forcing).  The previous parent used a
    # c[8]**2 * time ramp to manufacture onset; that linear-in-time term is
    # unphysical (it keeps driving conversion even after the plateau region of
    # a curve) and is a likely source of held-out and cross-protein shape error.
    # Removing it leaves a pure mechanism whose lag, burst and saturation are
    # all generated by the state dynamics, which improves half-response timing
    # generalization while also shrinking the constant count (8 < 9).
    #
    # Mechanistic terms, all gated by the depleting capacity (plateau - c) for
    # mass conservation and saturation:
    #   * source = s0 + s1*M0  -- primary nucleation + seed-driven onset; the
    #     constant part breaks the c=0 fixed point so unseeded curves still
    #     ignite, the M0 part shortens the lag when seed is present.
    #   * elongation  = k_e * c                    (linear autocatalysis)
    #   * secondary   = k_2 * c**2 * (1 + k_s*M0)   (surface-catalysed nucleation)
    #   * sharpening  = k_3 * c**3                  (next moment; steepens the
    #     mid-phase slope so the integrated trajectory matches the sharp
    #     sigmoidal burst that drives the dominant slope shape loss)
    # The whole growth flux is monomer-scaled by m0**p (well defined for m0>0).
    # The RHS is a smooth degree-4 polynomial in c with no divisions, logs, or
    # fractional powers, so it stays globally defined and numerically stable.
    # Knowles-Cohen reduced master equation in converted mass fraction c, with
    # a *bounded, self-extinguishing* primary-nucleation onset.  The two best
    # ancestors restored their score with an explicit-time onset term; the
    # weakness of a bare `c[8]*time*capacity` ramp is that it keeps injecting
    # conversion even near the plateau.  Here the onset flux is written as
    #
    #     source = (s0 + s_M*M0) * time
    #
    # but the ENTIRE growth flux (onset + autocatalysis) is gated by the single
    # depleting capacity (plateau - c).  Because capacity -> 0 at saturation,
    # the time-driven onset can never push conversion past the plateau, so the
    # lag is generated physically (slow nucleation accumulation early, when c
    # and the autocatalytic terms are negligible) yet the trajectory still
    # saturates cleanly.  This directly targets half-response/onset shape loss
    # without the runaway of a free additive time ramp.
    #
    # Autocatalytic feedbacks (all monomer-scaled by m0**p, well defined for
    # m0 > 0):
    #   * elongation  = k_e * c                       (linear growth)
    #   * secondary   = k_2 * c**2 * (1 + k_s*M0)      (surface-catalysed)
    #   * sharpening  = k_3 * c**3                     (steepens the burst)
    # The RHS is a smooth degree-4 polynomial in c with no divisions, logs, or
    # fractional powers, so it is globally defined and numerically stable.
    # Knowles/Cohen secondary-nucleation master equation in converted mass
    # fraction c, kept autonomous-friendly with a single bounded time-driven
    # onset and ALL flux gated by the depleting capacity for mass conservation.
    #
    # The dominant remaining error is the kinetic *shape* loss (slope profile +
    # half-response timing), and it is worst on the cross-protein eval-only
    # datasets.  The parent applied ONE global monomer power m0**c0 to every
    # term, which forces every mechanism to share the same monomer reaction
    # order.  Mechanistically this is wrong: elongation is ~first order in
    # monomer, whereas secondary nucleation has its own (often higher) reaction
    # order n2.  Decoupling the secondary-nucleation monomer order from the
    # elongation/onset order is exactly the degree of freedom that lets the lag
    # length and burst steepness adapt independently across proteins, directly
    # targeting the half-time/slope shape loss without changing the proven
    # backbone.  One extra exponent constant is added (10 < 13 limit).
    #
    # Stability: m0 > 0 so m0**power is real and smooth; all rate constants are
    # squared to stay positive; the RHS is a smooth low-degree polynomial in c
    # (capacity = plateau - c) with no divisions, logs, or fractional powers, so
    # it stays globally defined and numerically well conditioned.
    # Backbone unchanged: bounded time-driven onset + autocatalytic elongation,
    # secondary nucleation and a c**3 sharpening term, all gated by a depleting
    # capacity for mass conservation.  Two targeted shape-loss refinements:
    #
    #  (1) The secondary-nucleation monomer-order exponent c[9] gave essentially
    #      no payoff (9-constant ancestor scored 0.8910 vs 0.8914) yet adds a
    #      free exponent that destabilises constant fitting on small datasets.
    #      We reuse that degree of freedom for a *monomer-modulated plateau*:
    #      plateau = c[7] + c[9]**2 * monomer / (1 + monomer).  Different m0
    #      curves saturate toward slightly different normalized levels, so the
    #      near-saturation slope (a direct driver of the shape loss) can match
    #      each curve without changing the proven growth structure.  The
    #      monomer/(1+monomer) factor is a bounded, smooth Hill-1 saturation
    #      (monomer = m0 >= 0, so denominator >= 1, no singularity) that keeps
    #      the plateau finite and well conditioned across the m0 range.
    #
    #  (2) The onset is monomer-gated by base_scale already; no change there.
    # Hill-type SATURATING autocatalysis (cooperative secondary nucleation with
    # a self-limiting denominator), grafted onto the proven backbone instead of
    # replacing it.  Saturated secondary-nucleation theory (Meisl/Knowles 2016)
    # shows the catalytic flux saturates rather than growing as a bare power, so
    # we combine the linear elongation and quadratic secondary-nucleation
    # numerator over a single Hill-2 denominator (c[6]**2 + c**2):
    #
    #   auto = (k_e*c + k_2*c**2*(1 + k_s*M0)) / (c[6]**2 + c**2)
    #
    #   * near c=0 it is ~ k_e*c / c[6]**2  -> slow, monomer-gated ignition that
    #     together with the bounded onset sets the LAG length;
    #   * the denominator's relative slope is steepest near the half-saturation
    #     c == c[6], which fixes the burst INFLECTION / half-response time -- a
    #     single per-protein knob that directly targets timing shape loss;
    #   * at high c numerator and denominator both ~ c**2 so the flux SATURATES
    #     to a finite plateau, removing the unstable free cubic (c**3) term and
    #     working with the depleting capacity for a clean plateau.
    # The denominator is strictly positive (>= c[6]**2 > 0): no singularities,
    # globally smooth and bounded, so least-squares stays well conditioned.
    base_scale = monomer ** c[0]
    onset = (c[1] ** 2 + c[2] ** 2 * seed) * c[8] ** 2 * time
    elongation = c[3] ** 2 * concentration
    secondary = c[4] ** 2 * concentration ** 2 * (1 + c[5] ** 2 * seed)
    hill = (elongation + secondary) / (c[6] ** 2 + concentration ** 2)
    plateau = c[7] + c[9] ** 2 * monomer / (1 + monomer)
    capacity = plateau - concentration

    growth = base_scale * (onset + hill)
    expression = capacity * growth

    return evaluate_expression(
        expression,
        X_train,
        y_train,
        X_val,
        y_val,
        constants=c,
        initial_values=[0.5, 0.1, 0.3, 1.0, 1.0, 0.3, 0.5, 1.0, 0.5, 0.5],
    )


def run_discovery(
    X_train: NDArray,
    y_train: NDArray,
    X_val: NDArray,
    y_val: NDArray,
) -> dict[str, Any]:
    """Entry point used by the evaluator subprocess."""
    return evaluate_symbolic_candidate(X_train, y_train, X_val, y_val)


# EVOLVE-BLOCK-END


def _load_data():
    """Load the first dataset for local testing."""
    from evaluator import load_all_datasets

    datasets = load_all_datasets()
    name, X_train, X_val, y_train, y_val = datasets[0]
    print(f"Testing on: {name}")
    return X_train, X_val, y_train, y_val


if __name__ == "__main__":
    X_train, X_val, y_train, y_val = _load_data()
    result = run_discovery(X_train, y_train, X_val, y_val)
    print("equation:", result.get("equation"))
    print("nmse_val:", result.get("nmse_val"))
    print("combined_score:", result.get("combined_score"))
