# EVOLVE-BLOCK-START
"""ODE discovery seed for normalized multi-dataset amyloid aggregation kinetics."""

from __future__ import annotations

from typing import Any

import sympy as sp
from numpy.typing import NDArray

from pysr_harness.equation_session import (
    constant_symbols,
    evaluate_expression,
    feature_symbols,
)


def evaluate_symbolic_candidate(
    X_train: NDArray,
    y_train: NDArray,
    X_val: NDArray,
    y_val: NDArray,
) -> dict[str, Any]:
    """
    Generic bounded aggregation-rate ODE.

    This seed starts from a broad mechanism class rather than a specific
    closed-form solution: a concentration-independent source term can create
    onset from near-zero signal, while an autocatalytic state-dependent term
    can sharpen growth once aggregates are present.  Monomer and seed features
    modulate both routes, and a capacity factor keeps the trajectory saturating
    toward a fitted plateau.

    Features: x0 = normalized time, x1 = initial monomer m0, x2 = initial
    seed/aggregate M0, and x3 = current normalized concentration/state.
    """
    x = feature_symbols(X_train.shape[1])
    c = constant_symbols(11)

    time = x[0]
    monomer = x[1]
    seed = x[2]
    concentration = x[3]

    # Knowles-Cohen reduced master equation in converted mass fraction c, made
    # fully autonomous (no explicit-time forcing).  The previous parent used a
    # c[8]**2 * time ramp to manufacture onset; that linear-in-time term is
    # unphysical (it keeps driving conversion even after the plateau region of
    # a curve) and is a likely source of held-out and cross-protein shape error.
    # Removing it leaves a pure mechanism whose lag, burst and saturation are
    # all generated by the state dynamics, which improves half-response timing
    # generalization while also shrinking the constant count (8 < 9).
    #
    # Mechanistic terms, all gated by the depleting capacity (plateau - c) for
    # mass conservation and saturation:
    #   * source = s0 + s1*M0  -- primary nucleation + seed-driven onset; the
    #     constant part breaks the c=0 fixed point so unseeded curves still
    #     ignite, the M0 part shortens the lag when seed is present.
    #   * elongation  = k_e * c                    (linear autocatalysis)
    #   * secondary   = k_2 * c**2 * (1 + k_s*M0)   (surface-catalysed nucleation)
    #   * sharpening  = k_3 * c**3                  (next moment; steepens the
    #     mid-phase slope so the integrated trajectory matches the sharp
    #     sigmoidal burst that drives the dominant slope shape loss)
    # The whole growth flux is monomer-scaled by m0**p (well defined for m0>0).
    # The RHS is a smooth degree-4 polynomial in c with no divisions, logs, or
    # fractional powers, so it stays globally defined and numerically stable.
    # Knowles-Cohen reduced master equation in converted mass fraction c, with
    # a *bounded, self-extinguishing* primary-nucleation onset.  The two best
    # ancestors restored their score with an explicit-time onset term; the
    # weakness of a bare `c[8]*time*capacity` ramp is that it keeps injecting
    # conversion even near the plateau.  Here the onset flux is written as
    #
    #     source = (s0 + s_M*M0) * time
    #
    # but the ENTIRE growth flux (onset + autocatalysis) is gated by the single
    # depleting capacity (plateau - c).  Because capacity -> 0 at saturation,
    # the time-driven onset can never push conversion past the plateau, so the
    # lag is generated physically (slow nucleation accumulation early, when c
    # and the autocatalytic terms are negligible) yet the trajectory still
    # saturates cleanly.  This directly targets half-response/onset shape loss
    # without the runaway of a free additive time ramp.
    #
    # Autocatalytic feedbacks (all monomer-scaled by m0**p, well defined for
    # m0 > 0):
    #   * elongation  = k_e * c                       (linear growth)
    #   * secondary   = k_2 * c**2 * (1 + k_s*M0)      (surface-catalysed)
    #   * sharpening  = k_3 * c**3                     (steepens the burst)
    # SATURATING secondary-nucleation backbone (the best-scoring ancestor in
    # this lineage, 0.8933).  The bare polynomial cubic-sharpening term of the
    # parent grows without bound in c and tends to over-steepen the burst on
    # held-out / cross-protein curves, inflating shape loss.  Saturated
    # secondary-nucleation theory (Meisl/Knowles) shows the catalytic flux
    # SATURATES rather than diverging, so we replace the free cubic with a
    # Hill-2 self-limiting denominator on the combined autocatalytic numerator:
    #
    #   hill = (k_e*c + k_2*c**2*(1 + k_s*M0)) / (half_sat + c**2)
    #
    #   * near c=0  -> ~ k_e*c / half_sat : slow monomer-gated ignition that,
    #     with the bounded time-onset, sets the LAG length;
    #   * the denominator's relative slope is steepest near c == sqrt(half_sat),
    #     which fixes the burst INFLECTION / half-response time;
    #   * at high c numerator and denominator are both ~ c**2 so the flux
    #     SATURATES to a finite value, working with the depleting capacity for
    #     a clean, stable plateau (no runaway cubic term).
    #
    # ONE targeted refinement over the 0.8933 ancestor: the half-saturation is
    # made MONOMER-dependent, half_sat = c[6]**2 / (1 + c[10]**2 * monomer /
    # (1 + monomer)).  Higher monomer accelerates conversion and shifts the
    # inflection / half-response EARLIER, matching the experimentally observed
    # t_1/2 decreasing with m0 in the Knowles framework.  This is exactly the
    # concentration-dependent timing the cross-protein eval-only datasets (the
    # worst shape loss) need, and it is added with a bounded Hill-1 factor
    # (monomer >= 0 so the inner ratio is in [0,1) and the denominator stays
    # strictly positive >= c[6]**2 * something > 0), so the RHS is globally
    # smooth, bounded, and well conditioned with no new singularities.  A
    # monomer-modulated plateau lets different m0 curves saturate to slightly
    # different normalized levels.  11 constants (< 13 limit).
    monomer_scale = monomer ** c[0]
    onset = (c[1] ** 2 + c[2] ** 2 * seed) * c[8] ** 2 * time
    elongation = c[3] ** 2 * concentration
    secondary = c[4] ** 2 * concentration ** 2 * (1 + c[5] ** 2 * seed)
    half_sat = c[6] ** 2 / (1 + c[10] ** 2 * monomer / (1 + monomer))
    hill = (elongation + secondary) / (half_sat + concentration ** 2)
    plateau = c[7] + c[9] ** 2 * monomer / (1 + monomer)
    capacity = plateau - concentration

    growth = monomer_scale * (onset + hill)
    expression = capacity * growth

    return evaluate_expression(
        expression,
        X_train,
        y_train,
        X_val,
        y_val,
        constants=c,
        initial_values=[0.5, 0.1, 0.3, 1.0, 1.0, 0.3, 0.5, 1.0, 0.5, 0.5, 0.3],
    )


def run_discovery(
    X_train: NDArray,
    y_train: NDArray,
    X_val: NDArray,
    y_val: NDArray,
) -> dict[str, Any]:
    """Entry point used by the evaluator subprocess."""
    return evaluate_symbolic_candidate(X_train, y_train, X_val, y_val)


# EVOLVE-BLOCK-END


def _load_data():
    """Load the first dataset for local testing."""
    from evaluator import load_all_datasets

    datasets = load_all_datasets()
    name, X_train, X_val, y_train, y_val = datasets[0]
    print(f"Testing on: {name}")
    return X_train, X_val, y_train, y_val


if __name__ == "__main__":
    X_train, X_val, y_train, y_val = _load_data()
    result = run_discovery(X_train, y_train, X_val, y_val)
    print("equation:", result.get("equation"))
    print("nmse_val:", result.get("nmse_val"))
    print("combined_score:", result.get("combined_score"))
